name: Build latex and deploy to gh-pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: leplusorg/latex
      options: --user root

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: build.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
