name: Build latex and deploy to gh-pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: arkark/latexmk:full
      options: --user root

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          apt update && apt install -y make git fontconfig

      - name: Download Fonts
        run: |
          wget https://raw.githubusercontent.com/paulpeng-popo/cv/refs/heads/fonts/fonts.tar.gz
          tar -zxvf fonts.tar.gz

      - name: Install Fonts
        run: |
          mkdir -p ~/.local/share/fonts
          cp -r fonts/* ~/.local/share/fonts
          fc-cache -f -v

      - name: Build
        run: make

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
